server:
  port: 8002
  session-timeout: 30
  tomcat.max-threads: 500
  tomcat.uri-encoding: UTF-8
  tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH : true
  tomcat:
    min-spare-threads: 20
  connection-timeout: 10000
spring:
  profiles:
    active: prod
  jackson:
      serialization:
        write-dates-as-timestamps: true
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
