spring:
    http:
        encoding:
          force: true
          charset: UTF-8
          enabled: true
    datasource:
        name: test
        url: jdbc:mysql://119.3.15.241:3306/jk
        username: root
        password: Talkweb@2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath*:/com/talkweb/**/mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
logging:
  path: /Users/yko2008/Documents/logs
app:
  htmlpath: /Users/yko2008/work/twwork/湘西幸福家庭/svn/trunk/jk/api/manager/admin/src/main/resources/public
  imagehost: http://119.3.15.241:8002/